//RSADecrypt.java : Decrypts a file

//you will write a program to decrypt the encrypted file that has been generated by the 
//encryption procedure described earlier.
//The decryption algorithm should be runnable from a file named “RSADecrypt.java” (that is, this
//file should have the main method). The program will be called with the input encrypted file and
//the key file as arguments. The key file will be in the same format as described previously.
//The program will be invoked as :
//c:\> java RSADecrypt test.enc pri_key.txt
//where test.enc is the name of the file to be decrypted. The decrypted file that the program generates should be named “test.dec”.

public class RSADecrypt {

}
